name: Python Flask CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

  build:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if not installed
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing..."
            sudo apt update
            sudo apt install -y docker.io

            sudo systemctl start docker
            sudo systemctl enable docker

            sudo usermod -aG docker $USER
          fi

          # Verify Docker
          sudo docker --version

          # Pull latest image
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

          # Stop and remove old container
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true

          # Run new container
          sudo docker run -d \
            --name flask-app \ 
            -p 80:5000 \ 
            ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}